CREATE DATABASE DELHI_METRO;
USE DELHI_METRO;


SELECT COUNT(*)
FROM DELHI_METRO;

SELECT*
FROM DELHI_METRO;

DESCRIBE DELHI_METRO;

ALTER TABLE DELHI_METRO
MODIFY `OPENING DATE` DATE;

DESCRIBE DELHI_METRO;

SELECT COLUMN_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = "DELHI_METRO";

SELECT `OPENING DATE`
FROM DELHI_METRO;

SELECT*
FROM DELHI_METRO;

SELECT LINE, COUNT(*) AS TOTAL_STATIONS
FROM DELHI_METRO
GROUP BY LINE;

SELECT `STATION LAYOUT`, COUNT(*) AS COUNT
FROM DELHI_METRO
GROUP BY `STATION LAYOUT`;

SELECT LINE, SUM(
`Distance from Start (km)`
) AS TOTAL_KMS
FROM DELHI_METRO
GROUP BY LINE
ORDER BY TOTAL_KMS DESC;

SELECT*
FROM DELHI_METRO
ORDER BY `OPENING DATE` DESC
LIMIT 1;


SELECT*
FROM DELHI_METRO
ORDER BY `OPENING DATE` ASC
LIMIT 1;